name: Merge Deployment Branch

on:
  schedule:
    # minute hour day-of-month month-of-year day-of-week
    # Every 20 minutes Monday - Friday at from 19:00 - 22:00 UTC.
    - cron: "0,20,40 19-22 * * 1-5"

jobs:
  merge_deployment:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GITHUB_TOKEN: ${{ github.token }}
      DEPLOY_BRANCH: main
    steps:
      - uses: actions/checkout@v3
      - name: merge deployment pull request
        run: |
          pr_number=$(gh pr list \
                      --label deployment \
                      --search "-review:changes_requested" \
                      --limit 1 \
                      --json number \
                      --jq '.[].number')
          if [ ! -z "$pr_number" ]; then
            gh pr checkout $pr_number
            tag=deployment-$(git rev-parse --short HEAD)
            git tag $tag HEAD
            git push origin refs/tags/${tag}:refs/tags/${tag}
            git fetch origin main && git checkout main
            gh pr merge \
                --merge \
                --auto \
                --delete-branch \
                $pr_number
          fi
